// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bsnuppshabgicspclchz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJzbnVwcHNoYWJnaWNzcGNsY2h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxODkxNjksImV4cCI6MjA2NTc2NTE2OX0.WaViCrQVu0LYDqkZk5I7h4nXSIlg_ZZnreSco31JJKY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);